package com.mycompany.myapp;


import com.mycompany.GUI.Panier.HomePanierForm;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.mycompany.GUI.Panier.HomeStatsPanier;
import com.mycompany.GUI.Panier.PaymentForm;
import com.mycompany.GUI.Panier.VendeurCommandesForm;
import com.mycompany.GUI.Produits.HomeProduitsForm;
import com.mycompany.GUI.utilisateurs.LoginForm;
import com.mycompany.entites.Panier.FonctionPanier;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Form main;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme3");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        Log.bindCrashProtection(true);
    }
    
    public void start() throws IOException {
        if(current != null){
            current.show();
            return;
        }
         FonctionPanier.compterArticles();
       /* PaymentForm pf = new PaymentForm();
                 pf.getPsdTutorial().show();*/
      // VendeurCommandesForm vcf = new VendeurCommandesForm();
       // vcf.getPsdTutorial().show();
     HomeProduitsForm h = new HomeProduitsForm();h.getF().show();
      // HomePanierForm h = new HomePanierForm();
       //h.getPsdTutorial().show();
      /* LoginForm logForm = new LoginForm();
            logForm.getMain().show();*/
       
        FonctionPanier.compterArticles();
       /* HomeStatsPanier h = new HomeStatsPanier();
        h.getStatsForm().show();*/
        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
